### ISSUE TITLE
No support for ARM

### ISSUE THREAD

**Issue by Sunil-P** [Akemi/macOS-edid-modification#1]
Apple has disabled EDID fetch using ioreg on the new ARM Macs.

You might want to add this in the info page. IF you know of any other way, kindly let me know.

**Comment by Akemi** [comment]
apparently it doesn't work at all, even if you get the EDID by other means. 

https://gist.github.com/ejdyksen/8302862#gistcomment-3567356

**Comment by Sunil-P** [comment]
Hmm thats true and quite unfortunate. Is there any way to fetch raw EDID info from any other means though ? I need EDID to decode certain items from it.

**Comment by Akemi** [comment]
i quickly skimmed through the comments and apparently there is no way atm. the suggestions were to get the EDID from a different computer. which is really shit.

they started filing issues/feedback to apple here https://gist.github.com/adaugherity/7435890. maybe it's best to file one yourself at apple.

**Comment by Sunil-P** [comment]
Thank you, I will do that. Closing this issue.

**Comment by Akemi** [comment]
sry i couldn't really help much. if a solution ever pops up, or apple fixes it and i notice, i will update the instruction and most likely will comment on the issue here.
